/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gheorgheproject;

import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author gheor
 */
public class staffMangementAll extends javax.swing.JFrame {

    ManagerController con = new ManagerController();
    ArrayList list = new ArrayList();
    StaffRepoImpl staffRepo = new StaffRepoImpl();
    Connection conn;
    
    
    public staffMangementAll() {
        initComponents();
        //jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
        //jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
        //jTable1.getColumnModel().getColumn(2).setPreferredWidth(200);
    
    }
    
    public staffMangementAll(ManagerController control, Connection connection){
        initComponents();
        con = control;
        conn = connection;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        groupStaffGroupsRB = new javax.swing.ButtonGroup();
        staffManagementPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("staffManagementPU").createEntityManager();
        staff_1Query = java.beans.Beans.isDesignTime() ? null : staffManagementPUEntityManager.createQuery("SELECT s FROM Staff_1 s");
        staff_1List = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : staff_1Query.getResultList();
        staff_1Query1 = java.beans.Beans.isDesignTime() ? null : staffManagementPUEntityManager.createQuery("SELECT s FROM Staff_1 s");
        staff_1List1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : staff_1Query1.getResultList();
        staff_1Query2 = java.beans.Beans.isDesignTime() ? null : staffManagementPUEntityManager.createQuery("SELECT s FROM Staff_1 s");
        staff_1List2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : staff_1Query2.getResultList();
        staff_1Query3 = java.beans.Beans.isDesignTime() ? null : staffManagementPUEntityManager.createQuery("SELECT s FROM Staff_1 s");
        staff_1List3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : staff_1Query3.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        searchForFT = new javax.swing.JTextField();
        comboBoxAtribute = new javax.swing.JComboBox<>();
        searchBT = new javax.swing.JButton();
        managersRB = new javax.swing.JRadioButton();
        instructorsRB = new javax.swing.JRadioButton();
        Advisors = new javax.swing.JRadioButton();
        allRB = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        staff_idTF = new javax.swing.JTextField();
        first_nameTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        mobileNumberTF = new javax.swing.JTextField();
        addresTF = new javax.swing.JTextField();
        exitBT = new javax.swing.JButton();
        editStaffBT = new javax.swing.JButton();
        deleteStaffBT = new javax.swing.JButton();
        lastnameIN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        homeNumberTF = new javax.swing.JTextField();
        EmerContacLB = new javax.swing.JLabel();
        emergContaTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cityTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        countryTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        dateOfBirthTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        contractTF = new javax.swing.JTextField();
        departmentTF = new javax.swing.JTextField();
        salaryTF = new javax.swing.JTextField();
        addStaffBT = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        postCodeTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, staff_1List3, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${contract}"));
        columnBinding.setColumnName("Contract");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${salary}"));
        columnBinding.setColumnName("Salary");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${department}"));
        columnBinding.setColumnName("Department");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dateofbirth}"));
        columnBinding.setColumnName("Dateofbirth");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${country}"));
        columnBinding.setColumnName("Country");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${postcode}"));
        columnBinding.setColumnName("Postcode");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${city}"));
        columnBinding.setColumnName("City");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${address}"));
        columnBinding.setColumnName("Address");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${emergencynumber}"));
        columnBinding.setColumnName("Emergencynumber");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${homenumber}"));
        columnBinding.setColumnName("Homenumber");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${mobilenumber}"));
        columnBinding.setColumnName("Mobilenumber");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${email}"));
        columnBinding.setColumnName("Email");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${lastname}"));
        columnBinding.setColumnName("Lastname");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${firstname}"));
        columnBinding.setColumnName("Firstname");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${staffId}"));
        columnBinding.setColumnName("Staff Id");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Search:"));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Search for:");

        comboBoxAtribute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff ID", "First Name", "Last Name", "E-mail", "Mobile Number", "Home Number", "Emergency Contact Number", "Address", "City", "Country", "Date of Birth", "Contract Type", "Department", "Salary (Montly)" }));

        searchBT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gheorgheproject/images/icons8-find-user-male-48.png"))); // NOI18N
        searchBT.setText("Search");
        searchBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTActionPerformed(evt);
            }
        });

        groupStaffGroupsRB.add(managersRB);
        managersRB.setText("Managers");

        groupStaffGroupsRB.add(instructorsRB);
        instructorsRB.setText("Instructors");

        groupStaffGroupsRB.add(Advisors);
        Advisors.setText("Advisors");

        groupStaffGroupsRB.add(allRB);
        allRB.setText("All Departments");
        allRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allRBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchForFT, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboBoxAtribute, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(managersRB)
                    .addComponent(Advisors))
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allRB)
                    .addComponent(instructorsRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(searchBT, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(searchBT)
                    .addComponent(comboBoxAtribute)
                    .addComponent(searchForFT))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(managersRB)
                    .addComponent(instructorsRB))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Advisors)
                    .addComponent(allRB))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Employee Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Staff_ID:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("First Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("E-mail:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Mobile Number:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Address:");

        staff_idTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_idTFActionPerformed(evt);
            }
        });

        mobileNumberTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileNumberTFActionPerformed(evt);
            }
        });

        exitBT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exitBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gheorgheproject/images/icons8-shutdown-48.png"))); // NOI18N
        exitBT.setText("Logout");
        exitBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTActionPerformed(evt);
            }
        });

        editStaffBT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        editStaffBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gheorgheproject/images/icons8-edit-profile-skin-type-7-48.png"))); // NOI18N
        editStaffBT.setText("Edit Staff");
        editStaffBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStaffBTActionPerformed(evt);
            }
        });

        deleteStaffBT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deleteStaffBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gheorgheproject/images/icons8-denied-48.png"))); // NOI18N
        deleteStaffBT.setText("Delete Staff");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Last Name:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Home Number:");

        homeNumberTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeNumberTFActionPerformed(evt);
            }
        });

        EmerContacLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmerContacLB.setText("Emergency Contatact:");

        emergContaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergContaTFActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("City:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Country:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Date of Birth:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Contract:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Department:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Salary (Montly):");

        departmentTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentTFActionPerformed(evt);
            }
        });

        salaryTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryTFActionPerformed(evt);
            }
        });

        addStaffBT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addStaffBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gheorgheproject/images/icons8-add-user-group-woman-man-48.png"))); // NOI18N
        addStaffBT.setText("Add Staff");
        addStaffBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStaffBTActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Post Code:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(first_nameTF)
                            .addComponent(emailTF)
                            .addComponent(staff_idTF)
                            .addComponent(lastnameIN))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(EmerContacLB)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(dateOfBirthTF)
                        .addGap(179, 179, 179)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contractTF)
                            .addComponent(departmentTF))
                        .addGap(89, 89, 89)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mobileNumberTF)
                    .addComponent(addresTF)
                    .addComponent(homeNumberTF)
                    .addComponent(emergContaTF)
                    .addComponent(cityTF)
                    .addComponent(countryTF)
                    .addComponent(salaryTF)
                    .addComponent(postCodeTF))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addStaffBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteStaffBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editStaffBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addStaffBT, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(editStaffBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteStaffBT, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exitBT, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(postCodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salaryTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(101, 101, 101))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(staff_idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mobileNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(first_nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(homeNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastnameIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(EmerContacLB)
                            .addComponent(emergContaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(addresTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(dateOfBirthTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(contractTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(departmentTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(countryTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void departmentTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentTFActionPerformed

    private void emergContaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergContaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emergContaTFActionPerformed

    private void homeNumberTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeNumberTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeNumberTFActionPerformed

    private void editStaffBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStaffBTActionPerformed
        // edit staff bt
        new updateStaff().setVisible(true); //opens another form
        this.dispose(); // closes this form
    }//GEN-LAST:event_editStaffBTActionPerformed

    private void exitBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTActionPerformed
        new loginManager().setVisible(true); //opens another form
        this.dispose();
    }//GEN-LAST:event_exitBTActionPerformed

    private void mobileNumberTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileNumberTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileNumberTFActionPerformed

    private void staff_idTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff_idTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staff_idTFActionPerformed

    private void addStaffBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStaffBTActionPerformed
        
        // add staff Button
        new addStaff().setVisible(true); //opens another form
        this.dispose(); // closes this form
    }//GEN-LAST:event_addStaffBTActionPerformed

    private void allRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allRBActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_allRBActionPerformed

    private void salaryTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryTFActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
            
            int row = jTable1.getSelectedRow();            
            staff_idTF.setText(jTable1.getModel().getValueAt(row,0).toString());
            first_nameTF.setText(jTable1.getModel().getValueAt(row,1).toString());
            lastnameIN.setText(jTable1.getModel().getValueAt(row,2).toString());
            emailTF.setText(jTable1.getModel().getValueAt(row,3).toString());
            dateOfBirthTF.setText(jTable1.getModel().getValueAt(row,11).toString());
            contractTF.setText(jTable1.getModel().getValueAt(row,9).toString());
            departmentTF.setText(jTable1.getModel().getValueAt(row,13).toString());
            mobileNumberTF.setText(jTable1.getModel().getValueAt(row,4).toString());
            homeNumberTF.setText(jTable1.getModel().getValueAt(row,5).toString());
            emergContaTF.setText(jTable1.getModel().getValueAt(row,6).toString());
            addresTF.setText(jTable1.getModel().getValueAt(row,7).toString());
            cityTF.setText(jTable1.getModel().getValueAt(row,8).toString());
            postCodeTF.setText(jTable1.getModel().getValueAt(row,10).toString());
            salaryTF.setText(jTable1.getModel().getValueAt(row,14).toString());
            countryTF.setText(jTable1.getModel().getValueAt(row,11).toString());
            
    }//GEN-LAST:event_jTable1MouseClicked

    private void searchBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTActionPerformed
        // TODO add your handling code here:
        
        String data = con.viewALLDetails();
        searchForFT.setText(data);
    }//GEN-LAST:event_searchBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staffMangementAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staffMangementAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staffMangementAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staffMangementAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staffMangementAll().setVisible(true);
                StaffRepoImpl staffRepo = new StaffRepoImpl();
                ManagerController control = new ManagerController();
                Connection conn;
                
                String connectionURL = "jdbc:derby://localhost:1527/staffManagement";
                String uName = "manager";
                String uPass = "manager";
                
                try{
                    conn = DriverManager.getConnection(connectionURL ,uName, uPass);
                    System.out.println("Connect to database...");
                    if (conn != null){
                        ArrayList list = staffRepo.read(conn);
                        control.setStaff(list);
                        
                        staffMangementAll gui = new staffMangementAll(control, conn);
                        gui.setVisible(true);
                    } else {
                        System.out.println("null");
                    }//else
                                          
                } catch (SQLException ex){
                    System.out.println("Connection failed");
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Advisors;
    private javax.swing.JLabel EmerContacLB;
    private javax.swing.JButton addStaffBT;
    private javax.swing.JTextField addresTF;
    private javax.swing.JRadioButton allRB;
    private javax.swing.JTextField cityTF;
    private javax.swing.JComboBox<String> comboBoxAtribute;
    private javax.swing.JTextField contractTF;
    private javax.swing.JTextField countryTF;
    private javax.swing.JTextField dateOfBirthTF;
    private javax.swing.JButton deleteStaffBT;
    private javax.swing.JTextField departmentTF;
    private javax.swing.JButton editStaffBT;
    private javax.swing.JTextField emailTF;
    private javax.swing.JTextField emergContaTF;
    private javax.swing.JButton exitBT;
    private javax.swing.JTextField first_nameTF;
    private javax.swing.ButtonGroup groupStaffGroupsRB;
    private javax.swing.JTextField homeNumberTF;
    private javax.swing.JRadioButton instructorsRB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lastnameIN;
    private javax.swing.JRadioButton managersRB;
    private javax.swing.JTextField mobileNumberTF;
    private javax.swing.JTextField postCodeTF;
    private javax.swing.JTextField salaryTF;
    private javax.swing.JButton searchBT;
    private javax.swing.JTextField searchForFT;
    private javax.persistence.EntityManager staffManagementPUEntityManager;
    private java.util.List<gheorgheproject.Staff_1> staff_1List;
    private java.util.List<gheorgheproject.Staff_1> staff_1List1;
    private java.util.List<gheorgheproject.Staff_1> staff_1List2;
    private java.util.List<gheorgheproject.Staff_1> staff_1List3;
    private javax.persistence.Query staff_1Query;
    private javax.persistence.Query staff_1Query1;
    private javax.persistence.Query staff_1Query2;
    private javax.persistence.Query staff_1Query3;
    private javax.swing.JTextField staff_idTF;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
